language: python
python:
    - 2.7
before_install:

    # We do this to make sure we get dependencies
    - sudo apt-get update -qq
    - sudo apt-get install -qq libatlas-dev liblapack-dev gfortran
install: python setup.py install
notifications:
  email: true
#script: cd tests && sh TEST.sh
script: echo 'Not testing ATM'
